site_name: Docs - MinuKodu
site_url: https://docs.minukodu.net
site_author: Lukas Eßmann

copyright: >
  Copyright &copy; 2023 - 2025 Lukas Eßmann –
  <a href="#__consent">Change cookie settings</a>

theme:
  name: material
  features:
    - navigation.instant
    - toc.follow
    - content.code.annotate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
plugins:
  - search
  - privacy:
      enabled: true
      cache: true
      cache_dir: .cache/plugins/privacy
      assets: true
      assets_fetch: true
      assets_fetch_dir: assets/external
  - tags

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences